export const menuJson = {
    "allmenu":[
        {
            id:"1",
            name:"秋浦",
            targetUrl:"https://devgaoy.cn/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"2",
            name:"chatGPT学习宝典",
            targetUrl:"https://gpt.candobear.com/prompt",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"3",
            name:"奇舞周刊",
            targetUrl:"https://weekly.75.team/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"4",
            name:"js运行可视化",
            targetUrl:"https://www.jsv9000.app/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"5",
            name:"正则表达式",
            targetUrl:"https://regexr.com/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"6",
            name:"jsbench",
            targetUrl:"https://jsbench.me/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"7",
            name:"简历设计",
            targetUrl:"https://91huajian.cn/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"8",
            name:"echarts图表",
            targetUrl:"https://www.makeapie.cn/echarts",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"9",
            name:"茶杯狐 cupfox",
            targetUrl:"https://www.ixbdh.com/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"10",
            name:"集思录-低风险投资社区",
            targetUrl:"https://www.jisilu.cn/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"11",
            name:"30s code",
            targetUrl:"https://www.30secondsofcode.org/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"12",
            name:"图片压缩",
            targetUrl:"https://tinypng.com/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"13",
            name:"时间戳",
            targetUrl:"https://tool.lu/timestamp/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"14",
            name:"json解析",
            targetUrl:"https://www.rocschool.com/tool/jsonall/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"15",
            name:"can I Use",
            targetUrl:"https://caniuse.com/text-stroke",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"16",
            name:"followin",
            targetUrl:"https://followin.io/zh-Hans",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"17",
            name:"简历设计",
            targetUrl:"https://91huajian.cn/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"18",
            name:"ainav",
            targetUrl:"https://www.ainavpro.com/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"19",
            name:"一起用AI 先行于未来",
            targetUrl:"https://17yongai.com/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"20",
            name:"稿定设计",
            targetUrl:"https://www.gaoding.com/templates/f4814229",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"21",
            name:"低端电影",
            targetUrl:"https://ddys.art/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"22",
            name:"路过图床",
            targetUrl:"https://imgse.com/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"23",
            name:"可视化作品",
            targetUrl:"https://dribbble.com/YATINGZANG",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"24",
            name:"SaaS界面收集",
            targetUrl:"https://www.saasframe.io/saas",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"25",
            name:"金蝶设计系统",
            targetUrl:"https://www.kingdee.design/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"26",
            name:"AI帮个忙",
            targetUrl:"https://ai-toolbox.codefuture.top/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"27",
            name:"ai应用集",
            targetUrl:"https://aitools100.com/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"28",
            name:"AGE动画",
            targetUrl:"https://www.agemys.net/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"29",
            name:"书签地球",
            targetUrl:"https://www.bookmarkearth.com/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"30",
            name:"Learn Prompting",
            targetUrl:"https://learnprompting.org/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"31",
            name:"ChatGPT 快捷指令",
            targetUrl:"https://newzone.top/chatgpt/cn/",
            iconUrl:"",
            type:"nav"
        },
    ]
}