export const menuJson = {
    "allmenu":[
        {
            id:"1",
            name:"秋浦",
            targetUrl:"https://devgaoy.cn/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"2",
            name:"chatGPT学习宝典",
            targetUrl:"https://gpt.candobear.com/prompt",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"3",
            name:"奇舞周刊",
            targetUrl:"https://weekly.75.team/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"4",
            name:"js运行可视化",
            targetUrl:"https://www.jsv9000.app/",
            iconUrl:"",
            type:"nav"
        },
        {
            id:"5",
            name:"正则表达式",
            targetUrl:"https://regexr.com/",
            iconUrl:"",
            type:"nav"
        },
    ]
}